import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const root = resolve(import.meta.dirname, "..");
const html = await readFile(resolve(root, "site/index.html"), "utf8");
const css = await readFile(resolve(root, "site/styles.css"), "utf8");
const js = await readFile(resolve(root, "site/app.js"), "utf8");
assert.match(html, /<html lang="zh-CN">/);
assert.match(html, /id="participantView"/);
assert.match(html, /id="organizerView"/);
assert.match(html, /id="excludedNumbers"/);
assert.match(html, /max="41"/);
assert.match(html, /accept="image\/\*"[^>]+multiple/);
assert.match(html, /accept="\.zip,application\/zip"[^>]+multiple/);
assert.match(html, /图片仅在你的设备中处理/);
assert.match(html, /202521330001_张三_01\.jpg/);
assert.match(css, /\.number-cell\.duplicate/);
assert.match(css, /\.number-cell\.skipped/);
assert.match(js, /function cleanName/);
assert.match(js, /async function makeZip/);
assert.match(js, /function parseStoredZip/);
assert.match(js, /async function createContactSheet/);
assert.match(js, /const CODE_PREFIX='2025213300'/);
assert.match(js, /const MAX_NUMBER=41/);
assert.match(js, /function excludedNumbers/);
assert.match(js, /version:3/);
assert.match(js, /readonly/);
new Function(js);

const workerUrl = pathToFileURL(resolve(root, "dist/server/index.js")).href + `?v=${Date.now()}`;
const worker = (await import(workerUrl)).default;
const pageResponse = await worker.fetch(new Request("https://example.test/"));
assert.equal(pageResponse.status, 200);
assert.match(pageResponse.headers.get("content-type") || "", /text\/html/);
assert.match(pageResponse.headers.get("content-security-policy") || "", /connect-src 'none'/);
assert.match(await pageResponse.text(), /39 人一键汇总/);
const scriptResponse = await worker.fetch(new Request("https://example.test/app.js"));
assert.equal(scriptResponse.status, 200);
assert.match(scriptResponse.headers.get("content-type") || "", /javascript/);
assert.match(await scriptResponse.text(), /tumingjiang-submission/);
console.log("Validated participant packaging, organizer aggregation, contact sheet, responsive assets, and worker routes.");
