import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const root = resolve(import.meta.dirname, "..");
const html = await readFile(resolve(root, "site/index.html"), "utf8");
const css = await readFile(resolve(root, "site/styles.css"), "utf8");
const js = await readFile(resolve(root, "site/app.js"), "utf8");

assert.match(html, /<html lang="zh-CN">/);
assert.match(html, /本地批量命名工具/);
assert.match(html, /id="rosterInput"/);
assert.match(html, /id="peopleGrid"/);
assert.match(html, /id="downloadFinal"/);
assert.match(html, /照片不上传/);
assert.doesNotMatch(html, /参与者|负责人汇总台|个人照片包/);
assert.match(css, /\.person-card/);
assert.match(css, /\.export-bar/);
assert.match(js, /const CODE_PREFIX = '2025213300'/);
assert.match(js, /const MAX_NUMBER = 41/);
assert.match(js, /const MAX_PHOTOS = 2/);
assert.match(js, /function parseRoster/);
assert.match(js, /async function makeZip/);
assert.match(js, /async function buildFinalZip/);
assert.match(js, /照片汇总清单\.csv/);
assert.doesNotMatch(js, /localStorage|fetch\(/);
new Function(js);

const workerUrl = pathToFileURL(resolve(root, "dist/server/index.js")).href + `?v=${Date.now()}`;
const worker = (await import(workerUrl)).default;
const pageResponse = await worker.fetch(new Request("https://example.test/"));
assert.equal(pageResponse.status, 200);
assert.match(pageResponse.headers.get("content-type") || "", /text\/html/);
assert.match(pageResponse.headers.get("content-security-policy") || "", /connect-src 'none'/);
assert.match(await pageResponse.text(), /几十人的照片/);
const scriptResponse = await worker.fetch(new Request("https://example.test/app.js"));
assert.equal(scriptResponse.status, 200);
assert.match(scriptResponse.headers.get("content-type") || "", /javascript/);
assert.match(await scriptResponse.text(), /buildFinalZip/);
console.log("Validated local roster, one-or-two-photo assignment, unified naming, and final ZIP export.");
