import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const root = resolve(import.meta.dirname, "..");
const html = await readFile(resolve(root, "site/index.html"), "utf8");
const css = await readFile(resolve(root, "site/styles.css"), "utf8");
const js = await readFile(resolve(root, "site/app.js"), "utf8");

assert.match(html, /<html lang="zh-CN">/);
assert.match(html, /个人照片命名工具/);
assert.match(html, /id="personNumber"/);
assert.match(html, /id="personName"/);
assert.match(html, /id="photoPicker"[^>]+multiple/);
assert.match(html, /id="downloadPersonal"/);
assert.match(html, /别人看不到/);
assert.doesNotMatch(html, /负责人|汇总台|粘贴名单|管理端/);
assert.match(css, /\.photo-card/);
assert.match(css, /\.privacy-card/);
assert.match(js, /const CODE_PREFIX = '2025213300'/);
assert.match(js, /const MAX_NUMBER = 41/);
assert.match(js, /const MAX_PHOTOS = 2/);
assert.match(js, /function validateIdentity/);
assert.match(js, /async function makeZip/);
assert.match(js, /_照片包\.zip/);
assert.doesNotMatch(js, /localStorage|fetch\(/);
new Function(js);

const workerUrl = pathToFileURL(resolve(root, "dist/server/index.js")).href + `?v=${Date.now()}`;
const worker = (await import(workerUrl)).default;
const pageResponse = await worker.fetch(new Request("https://example.test/"));
assert.equal(pageResponse.status, 200);
assert.match(pageResponse.headers.get("content-type") || "", /text\/html/);
assert.match(pageResponse.headers.get("content-security-policy") || "", /connect-src 'none'/);
assert.match(await pageResponse.text(), /填自己的信息/);
const scriptResponse = await worker.fetch(new Request("https://example.test/app.js"));
assert.equal(scriptResponse.status, 200);
assert.match(scriptResponse.headers.get("content-type") || "", /javascript/);
assert.match(await scriptResponse.text(), /makeZip/);
console.log("Validated independent personal naming, one-or-two-photo selection, privacy, and ZIP export.");
